FROM python:3.14

# Set environment variables
ENV PYTHONUNBUFFERED=1

# Set work directory
WORKDIR /app

# Install dependencies
COPY requirements.txt /app/
RUN pip install --upgrade pip && \
    pip install --no-cache-dir -r requirements.txt

# Copy project
COPY . /app/

# Expose port
EXPOSE 8001

# Run start server (currently as there are no python script it will be with the base ./your-daemon-or-script.py)
CMD [ "python", "./your-daemon-or-script.py" ]